#!/usr/bin/env bash
set -e

if [[ "${MSYSTEM}" != "MINGW64" ]]; then
    echo "Please run this script in MSYS2 MinGW64 shell"
    exit 1
fi

# 脚本所在目录 -> 仓库根目录（不依赖固定路径，便于迁移）
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "${SCRIPT_DIR}")"

# QEMU源码目录
QEMU_SRC="${ROOT_DIR}/qemu"

# 构建目录
CONFIG_DIR="${QEMU_SRC}/qemu-configure"
BUILD_DIR="${QEMU_SRC}/qemu-build"

# 测试目录
TEST_DIR="${ROOT_DIR}/testcase"

echo "==> Enter QEMU source directory"
cd "${QEMU_SRC}"

echo "==> Creating configure/build directories"
mkdir -p "${CONFIG_DIR}"
mkdir -p "${BUILD_DIR}"

cd "${CONFIG_DIR}"

if [[ -f "config-host.mak" && -f "Makefile" ]]; then
    echo "==> Configure already completed, skipping configure step"
else
    echo "==> Running configure"
    ../configure \
        --prefix="${BUILD_DIR}" \
        --target-list=arm-softmmu \
        --enable-debug \
        --disable-docs
fi

echo "==> Building QEMU"
make -j16
echo "==> Build finished successfully"

echo "==> QEMU install prefix: ${BUILD_DIR}"
make install
echo "==> Install finished"

# --- Bundle runtime DLLs so the build is self-contained (runnable even when
#     the MSYS2 MINGW64 bin dir is NOT on PATH, e.g. from a plain PowerShell).
#     `make install` only copies QEMU's own files; the MinGW build dynamically
#     links against glib/pixman/SDL2/... which live in ${MINGW_PREFIX}/bin.
#     Here we resolve each exe's DLL dependency closure and copy them next to
#     the exes. Windows system DLLs (KERNEL32.dll etc.) are skipped because
#     they are not present under ${MINGW_PREFIX}/bin. ---
echo "==> Bundling runtime DLLs (self-contained build)"
# A stamp file records the DLL set from the last full bundle. On later builds
# we only `stat` those files: if they are all still present we skip, avoiding
# the slow recursive `objdump` scan (~1 min, ~100 subprocesses, each objdump
# on the big debug exe takes ~11 s) on every rebuild.
STAMP="${BUILD_DIR}/.runtime-dlls.stamp"

# Full dependency-closure scan + copy (only the missing files).
_bundle_runtime_dlls() {
    local dest="$1"; shift
    local -a queue=("$@")
    local seen=""
    local -a missing=()
    while ((${#queue[@]})); do
        local f="${queue[0]}"
        queue=("${queue[@]:1}")
        while IFS= read -r dll; do
            [[ -z "$dll" ]] && continue
            [[ "$seen" == *"|${dll}|"* ]] && continue
            if [[ -f "${MINGW_PREFIX}/bin/${dll}" ]]; then
                seen="${seen}|${dll}|"
                if [[ ! -f "${dest}/${dll}" ]]; then
                    missing+=("$dll")
                fi
                queue+=("${MINGW_PREFIX}/bin/${dll}")
            fi
        done < <(objdump -p "$f" 2>/dev/null | sed -n 's/.*DLL Name: *//p' | tr -d '\r')
    done
    if ((${#missing[@]} > 0)); then
        echo "  Copying ${#missing[@]} missing runtime DLL(s)..."
        local d
        for d in "${missing[@]}"; do
            cp -f "${MINGW_PREFIX}/bin/${d}" "$dest/"
        done
    fi
}

# Return 0 if a (re)bundle is needed, 1 if everything is already bundled.
_needs_bundle() {
    local dest="$1"; shift
    # stamp present?
    [[ -f "${dest}/.runtime-dlls.stamp" ]] || return 0
    # exe set unchanged (a new/removed exe may need different DLLs)?
    local cur exes
    cur="$(cd "${dest}" && ls -1 *.exe 2>/dev/null | sort | tr '\n' ' ')"
    exes="$(sed -n 's/^# exes: //p' "${dest}/.runtime-dlls.stamp")"
    [[ "${cur}" == "${exes}" ]] || return 0
    # every stamped DLL still present?
    local dll
    while IFS= read -r dll; do
        [[ -z "$dll" || "$dll" == \#* ]] && continue
        [[ -f "${dest}/${dll}" ]] || return 0
    done < "${dest}/.runtime-dlls.stamp"
    return 1
}

if _needs_bundle "${BUILD_DIR}"; then
    echo "  Bundling runtime DLLs (first run, or stamp missing / DLLs changed)..."
    _bundle_runtime_dlls "${BUILD_DIR}" "${BUILD_DIR}"/*.exe
    {
        echo "# runtime DLL bundle stamp (generated by qemu-build-msys2.sh)"
        echo "# exes: $(cd "${BUILD_DIR}" && ls -1 *.exe 2>/dev/null | sort | tr '\n' ' ')"
        cd "${BUILD_DIR}" && ls -1 *.dll 2>/dev/null
    } > "${STAMP}"
    echo "  Wrote stamp: ${STAMP}"
else
    echo "  Runtime DLLs already bundled, skipping copy (stamp: ${STAMP})."
fi
echo "==> DLL bundling finished"

echo "==> Running testcase starting"
${BUILD_DIR}/qemu-system-arm.exe -machine mps2-an505 -cpu cortex-m33 -m 16M -kernel ${TEST_DIR}/an505-qemu.elf -display sdl,show-cursor=on -serial stdio
echo "==> Running testcase finished"
